### ISSUE TITLE
Fail to detect GPU in 3.3.x on Mac OS 10.7-9

### ISSUE THREAD

**Issue by fabulouspanda** [luke-jr/bfgminer#305]
Version 3.3.0 seems to be unable to detect the GPU on Mac OS. It seems to have configured fine:

Configuration Options Summary:

```
  Enabled..Drivers.....: avalon bigpic bitforce bitfury_gpio cairnsmore cpu erupter icarus littlefury modminer opencl opencl:adl x6500 ztex 
    Disabled.Drivers.....: bfsb cpu:asm cpu:sse2 metabank opencl:sensors proxy 
      To enable opencl:sensors, install libsensors
      To enable proxy, install libmicrohttpd 0.9.5+ (getwork) or libevent 2.0.3+ (stratum)
    Enabled..Algorithms..: SHA256d scrypt 
    Disabled.Algorithms..: 
    Enabled..Options.....: ncurses 
    Disabled.Options.....: 
```

and it does still work for PGAs and CPU mining
